import type { Plugin } from 'vite';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

/**
 * Vite plugin to inject environment variables
 * Similar to scripts/inject-env.js but integrated with Vite
 */
export function injectEnvPlugin(mode: 'development' | 'production'): Plugin {
    return {
        name: 'inject-env',
        generateBundle() {
            const envFile = resolve(process.cwd(), `.env.${mode}`);
            const envVars: Record<string, string> = {};

            // Default values
            const defaults: Record<string, string> = {
                VITE_APP_NAME: mode === 'production' ? 'DebtLite' : 'DebtLite (Dev)',
                VITE_STORAGE_TYPE: 'localStorage',
                VITE_API_URL: 'http://localhost:3000/api',
                VITE_MAX_PLANS: '50',
                VITE_MAX_PLAN_AMOUNT: '1000000000',
                VITE_MAX_PLAN_MONTHS: '120',
            };

            // Read .env file if it exists
            if (existsSync(envFile)) {
                const envContent = readFileSync(envFile, 'utf-8');

                // Parse .env file
                envContent.split('\n').forEach((line) => {
                    line = line.trim();
                    if (line && !line.startsWith('#')) {
                        const [key, ...valueParts] = line.split('=');
                        if (key && valueParts.length > 0) {
                            const value = valueParts.join('=').trim();
                            envVars[key.trim()] = value;
                        }
                    }
                });
            } else {
                console.warn(`⚠️  Environment file ${envFile} not found. Using defaults.`);
                Object.assign(envVars, defaults);
            }

            // Merge with defaults (env file values override defaults)
            const finalEnvVars = { ...defaults, ...envVars };

            // Generate env-config.js content
            const envConfigContent = `// Auto-generated by Vite plugin
window.__ENV__ = ${JSON.stringify(finalEnvVars, null, 2)};
`;

            // Emit the file
            this.emitFile({
                type: 'asset',
                fileName: 'env-config.js',
                source: envConfigContent,
            });
        },
    };
}

