import type { Plugin } from 'vite';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

/**
 * Vite plugin to inject environment variables
 * Similar to scripts/inject-env.js but integrated with Vite
 */
export function injectEnvPlugin(mode: 'development' | 'production'): Plugin {
    return {
        name: 'inject-env',
        generateBundle() {
            const envFile = resolve(process.cwd(), `.env.${mode}`);
            const envVars: Record<string, string> = {};

            // Default values
            const defaults: Record<string, string> = {
                VITE_APP_NAME: mode === 'production' ? 'DebtLite' : 'DebtLite (Dev)',
                VITE_STORAGE_TYPE: 'localStorage',
                VITE_API_URL: 'http://localhost:3000/api',
                VITE_MAX_PLANS: '50',
                VITE_MAX_PLAN_AMOUNT: '1000000000',
                VITE_MAX_PLAN_MONTHS: '120',
            };

            // Read from process.env first (Vercel/CI/CD injects variables here)
            // Check for VITE_ prefixed variables in process.env
            Object.keys(process.env).forEach((key) => {
                if (key.startsWith('VITE_')) {
                    const value = process.env[key];
                    if (value !== undefined) {
                        envVars[key] = value;
                    }
                }
            });

            // Read .env file if it exists (for local development)
            if (existsSync(envFile)) {
                const envContent = readFileSync(envFile, 'utf-8');

                // Parse .env file
                envContent.split('\n').forEach((line) => {
                    line = line.trim();
                    if (line && !line.startsWith('#')) {
                        const [key, ...valueParts] = line.split('=');
                        if (key && valueParts.length > 0) {
                            const value = valueParts.join('=').trim();
                            // Only use .env file values if not already set from process.env
                            if (!envVars[key.trim()]) {
                                envVars[key.trim()] = value;
                            }
                        }
                    }
                });
            } else if (Object.keys(envVars).length === 0) {
                // Only warn if no variables from process.env AND no .env file
                console.warn(`⚠️  Environment file ${envFile} not found. Using defaults.`);
            }

            // Merge with defaults (process.env > .env file > defaults)
            const finalEnvVars = { ...defaults, ...envVars };

            // Generate env-config.js content
            const envConfigContent = `// Auto-generated by Vite plugin
window.__ENV__ = ${JSON.stringify(finalEnvVars, null, 2)};
`;

            // Emit the file
            this.emitFile({
                type: 'asset',
                fileName: 'env-config.js',
                source: envConfigContent,
            });
        },
    };
}

